### ISSUE TITLE
Visualization with IGV on VCF files

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy-helm#117] opened 2020-02-19 18:58 UTC
Cannot load IGV local on VCF files when running on a GVL 5.0

(Example in this tutorial https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/non-dip/tutorial.html#looking-at-the-data)

**Comment by almahmoud** [comment] 2020-02-19 21:38
This might be related to `sanitize_whitelist` like JBrowse, but because IGV is not a real tool, not sure if it is (or how to add it) or if there is something else going on. Thoughts @afgane @dannon ?

**Comment by dannon** [comment] 2020-02-19 21:47
Hey, thanks for the ping.  Do you have a link to a history I can look at?  If not, I can build one from that guide I guess.

**Comment by almahmoud** [comment] 2020-02-19 22:05
I can reproduce on a GVL instance

**Comment by almahmoud** [comment] 2020-02-20 19:38
Quast was the one where adding to `sanitize_whitelist` didn't fix the rendering for the HTML output: https://github.com/galaxyproject/galaxy-helm/issues/118

**Comment by almahmoud** [comment] 2020-02-27 19:40
Closing this given that behavior is same as Main and IGV just needs a local component.

**Closed by almahmoud** 2020-02-27 19:40 UTC
